# Generated by Django 4.2.7 on 2025-12-15 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("twitter", "Twitter"),
                            ("snapchat", "Snapchat"),
                            ("meta", "Meta"),
                            ("tiktok", "TikTok"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "external_account_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("access_token", models.TextField(blank=True, null=True)),
                ("access_token_secret", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("error", "Error"),
                        ],
                        default="connected",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_accounts",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "ad_accounts",
                "ordering": ["-created_at"],
            },
        ),
    ]
