# Generated by Django 4.2.7 on 2025-12-08 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("text", "Text"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file_url", models.URLField(blank=True, null=True)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "generated_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("generation_prompt", models.TextField(blank=True, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("ar", "Arabic"), ("en", "English")],
                        default="ar",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_assets",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "content_assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("video", "Video Template"),
                            ("image", "Image Template"),
                            ("text", "Text Template"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("fashion", "Fashion"),
                            ("electronics", "Electronics"),
                            ("food", "Food & Beverage"),
                            ("beauty", "Beauty & Cosmetics"),
                            ("automotive", "Automotive"),
                            ("real_estate", "Real Estate"),
                            ("health", "Health & Wellness"),
                            ("education", "Education"),
                            ("travel", "Travel & Tourism"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("ramadan", "Ramadan"),
                            ("eid", "Eid"),
                            ("national_day", "National Day"),
                            ("new_year", "New Year"),
                            ("summer", "Summer"),
                            ("winter", "Winter"),
                            ("back_to_school", "Back to School"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("template_data", models.JSONField()),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_templates",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "content_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("product_url", models.URLField(blank=True, null=True)),
                ("script", models.TextField(blank=True, null=True)),
                ("avatar_settings", models.JSONField(blank=True, default=dict)),
                ("brand_settings", models.JSONField(blank=True, default=dict)),
                ("language", models.CharField(default="ar", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "generated_video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_projects",
                        to="content_creation.contentasset",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content_creation.contenttemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="video_project_variations",
                        to="content_creation.contentasset",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_projects",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "video_projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text Generation"),
                            ("image", "Image Generation"),
                            ("video", "Video Generation"),
                            ("voice", "Voice Generation"),
                            ("script", "Script Generation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("stability", "Stability AI"),
                            ("elevenlabs", "ElevenLabs"),
                            ("heygen", "HeyGen"),
                            ("synthesia", "Synthesia"),
                            ("runway", "Runway ML"),
                        ],
                        max_length=100,
                    ),
                ),
                ("prompt", models.TextField()),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content_creation.contentasset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_jobs",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "generation_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_url", models.URLField()),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="SAR", max_length=3)),
                ("images", models.JSONField(blank=True, default=list)),
                ("features", models.JSONField(blank=True, default=list)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("brand", models.CharField(blank=True, max_length=255, null=True)),
                ("analysis_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_analyses",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "product_analyses",
                "ordering": ["-created_at"],
                "unique_together": {("workspace", "product_url")},
            },
        ),
    ]
